[build]
  publish = "dist"
  command = "./setup_ssh.sh && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  GIT_SSH_COMMAND = "ssh -i /tmp/deploy_key -o StrictHostKeyChecking=accept-new"
  NODE_VERSION = "16"