[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
YARN_CACHE_FOLDER = "/tmp/netlify-cache"

[build.environment]
  NODE_VERSION = "16"